# Generated by Django 4.0.3 on 2022-03-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('search_keyword', models.CharField(max_length=70)),
                ('search_time', models.DateTimeField(auto_now=True)),
                ('search_result', models.CharField(max_length=150)),
            ],
        ),
    ]
