# Generated by Django 4.0.3 on 2022-03-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_remove_user_id_alter_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
