# Generated by Django 4.0.3 on 2022-03-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=70)),
                ('search_date', models.DateField()),
                ('keywords', models.CharField(max_length=200)),
                ('result_list', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Search',
        ),
        migrations.DeleteModel(
            name='UserDes',
        ),
    ]
