# Generated by Django 4.0.3 on 2022-03-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_searchhistory_delete_search_delete_userdes'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='search_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
