# Generated by Django 4.0.3 on 2022-03-02 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_searchhistory_search_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='search_date',
        ),
    ]
