# Generated by Django 4.0.3 on 2022-03-03 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_remove_searchhistory_search_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='search_time',
        ),
    ]
