# Generated by Django 4.0.3 on 2022-03-03 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0008_remove_searchhistory_search_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='search_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 4, 1, 54, 35, 399471)),
        ),
    ]
